"""Add is_unifi_os to unifi_config

Revision ID: 48205017a8b9
Revises: fe4b29427755
Create Date: 2025-12-05 18:30:05.862191+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48205017a8b9'
down_revision: Union[str, None] = 'fe4b29427755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unifi_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unifi_os', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unifi_config', schema=None) as batch_op:
        batch_op.drop_column('is_unifi_os')

    # ### end Alembic commands ###
