"""Add Threat Watch tables

Revision ID: 343c9599c876
Revises: 
Create Date: 2025-12-02 01:46:15.181572+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343c9599c876'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unifi_event_id', sa.String(), nullable=False),
    sa.Column('flow_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('src_port', sa.Integer(), nullable=True),
    sa.Column('src_mac', sa.String(), nullable=True),
    sa.Column('dest_ip', sa.String(), nullable=True),
    sa.Column('dest_port', sa.Integer(), nullable=True),
    sa.Column('dest_mac', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('app_protocol', sa.String(), nullable=True),
    sa.Column('interface', sa.String(), nullable=True),
    sa.Column('src_country', sa.String(), nullable=True),
    sa.Column('src_city', sa.String(), nullable=True),
    sa.Column('src_latitude', sa.Float(), nullable=True),
    sa.Column('src_longitude', sa.Float(), nullable=True),
    sa.Column('src_asn', sa.String(), nullable=True),
    sa.Column('src_org', sa.String(), nullable=True),
    sa.Column('dest_country', sa.String(), nullable=True),
    sa.Column('dest_city', sa.String(), nullable=True),
    sa.Column('dest_latitude', sa.Float(), nullable=True),
    sa.Column('dest_longitude', sa.Float(), nullable=True),
    sa.Column('dest_asn', sa.String(), nullable=True),
    sa.Column('dest_org', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threats_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threats_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_events_dest_ip'), ['dest_ip'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_events_src_ip'), ['src_ip'], unique=False)
        batch_op.create_index('ix_threats_events_src_ip_timestamp', ['src_ip', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_threats_events_timestamp_severity', ['timestamp', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_threats_events_unifi_event_id'), ['unifi_event_id'], unique=True)

    op.create_table('threats_webhook_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('webhook_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('min_severity', sa.Integer(), nullable=False),
    sa.Column('event_alert', sa.Boolean(), nullable=False),
    sa.Column('event_block', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threats_webhook_config')
    with op.batch_alter_table('threats_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threats_events_unifi_event_id'))
        batch_op.drop_index('ix_threats_events_timestamp_severity')
        batch_op.drop_index(batch_op.f('ix_threats_events_timestamp'))
        batch_op.drop_index('ix_threats_events_src_ip_timestamp')
        batch_op.drop_index(batch_op.f('ix_threats_events_src_ip'))
        batch_op.drop_index(batch_op.f('ix_threats_events_severity'))
        batch_op.drop_index(batch_op.f('ix_threats_events_dest_ip'))
        batch_op.drop_index(batch_op.f('ix_threats_events_category'))

    op.drop_table('threats_events')
    # ### end Alembic commands ###
